import { readFileSync } from 'node:fs'
import { resolve } from 'node:path'
import { cwd } from 'node:process'

import { defineConfig } from 'vite'

export default defineConfig((params) => {
  const define = {
    'process.env.NODE_ENV': `'${params.mode}'`,
  }

  const dedupe = [
    '@apollo/client',
    'final-form',
    'react',
    'react-dom',
    'react-router-dom',
    'react-final-form',
    'react-final-form-arrays',
    'react-intl',
    'react-table',
    'styled-components',
  ]

  const plugins = []

  const reactOptions = {
    // https://github.com/alloc/vite-react-jsx/issues/10#issuecomment-1115328902
    jsxRuntime: 'classic',
  }

  try {
    plugins.push((await import('@vitejs/plugin-react-swc')).default(reactOptions))
  } catch {
    plugins.push((await import('@vitejs/plugin-react')).default(reactOptions))
  }

  const project = JSON.parse(readFileSync('./package.json'))

  let emptyOutDir = true
  let minify = true

  switch (params.mode) {
    case 'development':
      minify = false

      try {
        JSON.parse(readFileSync(('./linked-deps.json'))).forEach(dependency =>
          dedupe.push(dependency))
      } catch {}

      break

    case 'production':
      // Preserve the declaration files generated by TypeScript.
      emptyOutDir = false

      break
  }

  return {
    build: {
      emptyOutDir,
      lib: {
        entry: resolve(cwd(), 'src/index.ts'),
        fileName: 'index',
        formats: ['cjs', 'es'],
      },
      minify,
      rollupOptions: {
        external: Object.keys(project.peerDependencies),
      },
      sourcemap: true,
    },
    define,
    plugins,
    resolve: {
      alias: {
        '@' : resolve(cwd(), 'src'),
        'querystring': 'qs',
        'polygon-clipping': 'polygon-clipping/dist/polygon-clipping.cjs.js',
      },
      dedupe,
    },
  }
})
